"""The GPU surface: eight RTX 5090s, and everything that has to agree.

Claiming a GPU is not one command. `nvidia-smi` has to agree with lspci,
with /proc/driver/nvidia, with the device nodes, with lsmod, with dpkg and
with dmesg -- and every one of those is a place to contradict yourself. So
the facts live here once and every reader derives from them.

Measured, not guessed. The table geometry and every column format were
taken from real nvidia-smi output captured through a pty on two different
cards -- an RTX 5090 laptop part and an RTX 4070 Ti -- and the renderer
below reproduces both byte for byte before it is trusted on this persona.

The card's own numbers are the desktop RTX 5090's and were researched
rather than photographed, because no desktop 5090 was in reach:

    PCI device      10de:2b85 rev a1, GB202-300-A1
    memory          32607 MiB as nvidia-smi reports it, not 32768
    power cap       575 W
    compute cap     12.0

The laptop part differs on every one of those -- 10de:2c58, GB203M, 24463
MiB, 175 W -- which is exactly why it was used for format only.

Driver 595.84 and CUDA 13.2 were measured together on a real card, so the
pair is real rather than two plausible numbers put side by side.
"""

GPU_COUNT = 8
GPU_NAME = "NVIDIA GeForce RTX 5090"
GPU_MEM_MIB = 32607
GPU_POWER_CAP = 575
GPU_DRIVER = "595.84"
GPU_CUDA = "13.2"
GPU_COMPUTE_CAP = "12.0"
GPU_VBIOS = "98.02.3C.00.B7"

#: The inforom image version. A real GeForce answers inforom.img with a
#: version string and inforom.power with [N/A]; ours answered [N/A] to
#: both, which --help-query-gpu declares as queryable either way.
GPU_INFOROM_IMG = "G002.0000.00.03"
GPU_PCI_DEVID = "0x2B8510DE"
GPU_PCI_SUBDEV = "0x162C10DE"
GPU_ARCH = "GB202"
GPU_MAX_GRAPHICS_MHZ = 2947
GPU_MAX_MEM_MHZ = 14001

#: One card per x16 slot, spaced the way a board with eight of them is.
GPU_BUS_IDS = ("00000000:01:00.0", "00000000:21:00.0", "00000000:41:00.0",
               "00000000:61:00.0", "00000000:81:00.0", "00000000:a1:00.0",
               "00000000:c1:00.0", "00000000:e1:00.0")

#: Stable per-card UUIDs. Fixed rather than random: an attacker who runs
#: nvidia-smi twice, or who comes back tomorrow, must see the same cards.
GPU_UUIDS = (
    "GPU-9a5f0c31-6d42-4e18-b7a0-2c1f8e6b4d09",
    "GPU-1c8e4b70-33a9-4f52-9d61-7e0a5c2f8b34",
    "GPU-6b2d9f45-8c17-4a63-85fe-0d3b7a1c6e28",
    "GPU-e07a3c68-2b54-49d1-a3c7-6f8b0e4d29a5",
    "GPU-4d1b8e29-7f60-4c35-92a8-5b3e0c7f1d64",
    "GPU-83f6c02a-19d7-4b8e-a06f-2e9c5d4b7038",
    "GPU-2e9c7b14-5a38-4d70-b1c6-98f0a3e5c27b",
    "GPU-b5408d63-c72e-4915-8fa2-31d6b0e97c45",
)


def table_geometry():
    """(total width, the three column widths), measured from real output."""
    return 91, (41, 24, 22)


def _name_cell(name):
    """The Name column truncates with an ellipsis, measured at 27 wide."""
    return name if len(name) <= 27 else name[:24] + "..."


def gpu_block(idx, persist, busid, disp, ecc, fan, temp, perf,
              draw, cap, used, total, util, cmode, mig, name=GPU_NAME):
    """One card's three lines. Reproduces real nvidia-smi byte for byte."""
    left = "%4d  %s" % (idx, _name_cell(name))
    a1 = left + persist.rjust(41 - len(left) - 1) + " "
    a2 = "   %s %3s " % (busid, disp)
    a3 = ecc.rjust(21) + " "
    b1 = "%4s%6s%6s%15dW / %4dW " % (fan, "%dC" % temp, perf, draw, cap)
    b2 = "%8dMiB / %6dMiB " % (used, total)
    b3 = "%7d%%%13s " % (util, cmode)
    c1 = " " * 41
    c2 = " " * 24
    c3 = mig.rjust(21) + " "
    return ["|%s|%s|%s|" % (a1, a2, a3),
            "|%s|%s|%s|" % (b1, b2, b3),
            "|%s|%s|%s|" % (c1, c2, c3)]


def header(now_text):
    """The banner and column titles, exactly as measured."""
    top = "+" + "-" * 89 + "+"
    # Field widths taken off the measured banner: 12 + 23 + 16 + 15 + 14 + 9
    # comes to exactly the 89 columns between the borders.
    ver = (" NVIDIA-SMI " + GPU_DRIVER.ljust(23)
           + "Driver Version: " + GPU_DRIVER.ljust(15)
           + "CUDA Version: " + GPU_CUDA.ljust(9))
    sep = "+" + "-" * 41 + "+" + "-" * 24 + "+" + "-" * 22 + "+"
    h1 = "| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |"
    h2 = "| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |"
    h3 = "|                                         |                        |               MIG M. |"
    bar = "|" + "=" * 41 + "+" + "=" * 24 + "+" + "=" * 22 + "|"
    return [now_text, top, "|" + ver + "|", sep, h1, h2, h3, bar]


#: The field lists `nvidia-smi --help-query-*` prints.
#:
#: Every one of these fell through to the dashboard: asking
#: `nvidia-smi --help-query-compute-apps` drew the eight-GPU table, which
#: no real driver does for a help switch and which reads as an emulator
#: the moment anyone looks. Captured verbatim from a real driver rather
#: than written: the wording, the blank lines and the trailing newline are
#: the tool's own. The persona reports 595.84 and this came off 580.142 --
#: the queryable field list is driver-stable, and inventing the prose
#: would have been the more detectable choice.
HELP_QUERY = {
    'gpu':
        'List of valid properties to query for the switch "--query-gpu":\n'
        '\n'
        '"timestamp"\n'
        'The timestamp of when the query was made in format "YYYY/MM/DD HH:MM:SS.msec".\n'
        '\n'
        '"driver_version"\n'
        'The version of the installed NVIDIA display driver. This is an alphanumeric string.\n'
        '\n'
        'Section about vgpu_driver_capability properties\n'
        'Retrieves information about driver level caps.\n'
        '\n'
        '"vgpu_driver_capability.heterogenous_multivGPU"\n'
        'Whether heterogeneuos multi-vGPU is supported by driver.\n'
        '\n'
        '"count"\n'
        'The number of NVIDIA GPUs in the system.\n'
        '\n'
        '"name" or "gpu_name"\n'
        'The official product name of the GPU. This is an alphanumeric string. For all products.\n'
        '\n'
        '"serial" or "gpu_serial"\n'
        'This number matches the serial number physically printed on each board. It is a globally unique immutable alphanumeric value.\n'
        '\n'
        '"uuid" or "gpu_uuid"\n'
        'This value is the globally unique immutable alphanumeric identifier of the GPU. It does not correspond to any physical label on the board.\n'
        '\n'
        '"pci.bus_id" or "gpu_bus_id"\n'
        'PCI bus id as "domain:bus:device.function", in hex.\n'
        '\n'
        '"pci.domain"\n'
        'PCI domain number, in hex.\n'
        '\n'
        '"pci.bus"\n'
        'PCI bus number, in hex.\n'
        '\n'
        '"pci.device"\n'
        'PCI device number, in hex.\n'
        '\n'
        '"pci.baseClass"\n'
        'PCI Base Classcode, in hex.\n'
        '\n'
        '"pci.subClass"\n'
        'PCI Sub Classcode, in hex.\n'
        '\n'
        '"pci.device_id"\n'
        'PCI vendor device id, in hex\n'
        '\n'
        '"pci.sub_device_id"\n'
        'PCI Sub System id, in hex\n'
        '\n'
        'Section about vgpu_device_capability properties\n'
        'Retrieves information about device level caps.\n'
        '\n'
        '"vgpu_device_capability.fractional_multiVgpu"\n'
        'Fractional vGPU profiles on this GPU can be used in multi-vGPU configurations.\n'
        '\n'
        '"vgpu_device_capability.heterogeneous_timeSlice_profile"\n'
        'Supports concurrent execution of timesliced vGPU profiles of differing types.\n'
        '\n'
        '"vgpu_device_capability.heterogeneous_timeSlice_sizes"\n'
        'Supports concurrent execution of timesliced vGPU profiles of differing framebuffer sizes.\n'
        '\n'
        '"vgpu_device_capability.homogeneous_placements"\n'
        'Supports reporting of placements of timesliced vGPU profiles of identical framebuffer sizes.\n'
        '\n'
        '"vgpu_device_capability.mig_timeSlicing"\n'
        'Reports whether GPU supports timesliced vGPU on MIG.\n'
        '\n'
        '"vgpu_device_capability.mig_timeSlicing_mode"\n'
        'Reports whether MIG timesliced mode is enabled or not.\n'
        '\n'
        '"pcie.link.gen.current"\n'
        'The current PCI-E link generation. These may be reduced when the GPU is not in use. Deprecated, use pcie.link.gen.gpucurrent instead.\n'
        '\n'
        '"pcie.link.gen.gpucurrent"\n'
        'The current PCI-E link generation. These may be reduced when the GPU is not in use.\n'
        '\n'
        '"pcie.link.gen.max"\n'
        'The maximum PCI-E link generation possible with this GPU and system configuration. For example, if the GPU supports a higher PCIe generation than the system supports then this reports the system PCIe generation.\n'
        '\n'
        '"pcie.link.gen.gpumax"\n'
        'The maximum PCI-E link generation supported by this GPU.\n'
        '\n'
        '"pcie.link.gen.hostmax"\n'
        'The maximum PCI-E link generation supported by the root port corresponding to this GPU.\n'
        '\n'
        '"pcie.link.width.current"\n'
        'The current PCI-E link width. These may be reduced when the GPU is not in use.\n'
        '\n'
        '"pcie.link.width.max"\n'
        'The maximum PCI-E link width possible with this GPU and system configuration. For example, if the GPU supports a higher PCIe generation than the system supports then this reports the system PCIe generation.\n'
        '\n'
        '"index"\n'
        'Zero based index of the GPU. Can change at each boot.\n'
        '\n'
        '"display_mode"\n'
        'Deprecated, do not use.\n'
        '\n'
        '"display_attached"\n'
        'A flag that indicates whether a physical display (e.g. monitor) is currently connected to any of the GPU\'s connectors. "Yes" indicates an attached display. "No" indicates otherwise.\n'
        '\n'
        '"display_active"\n'
        'A flag that indicates whether a display is initialized on the GPU\'s (e.g. memory is allocated on the device for display). Display can be active even when no monitor is physically attached. "Enabled" indicates an active display. "Disabled" indicates otherwise.\n'
        '\n'
        '"persistence_mode"\n'
        'A flag that indicates whether persistence mode is enabled for the GPU. Value is either "Enabled" or "Disabled". When persistence mode is enabled the NVIDIA driver remains loaded even when no active clients, such as X11 or nvidia-smi, exist. This minimizes the driver load latency associated with running dependent apps, such as CUDA programs. Linux only.\n'
        '\n'
        '"addressing_mode"\n'
        'A flag that indicates the type of addressing mode enabled for the GPU. Value is either "HMM" or "ATS" or "None". When the mode is HMM, system allocated memory (malloc, mmap) is addressable from the device (GPU), via software-based mirroring of the CPU\'s page tables, on the GPU. When the mode is ATS, system allocated memory (malloc, mmap) is addressable from the device (GPU), via Address Translation Services. This means that there is (effectively) a single set of page tables, and the CPU and GPU both use them. The mode is None when neither HMM nor ATS is active. Linux only.\n'
        '\n'
        '"accounting.mode"\n'
        'A flag that indicates whether accounting mode is enabled for the GPU. Value is either "Enabled" or "Disabled". When accounting is enabled statistics are calculated for each compute process running on the GPU.Statistics can be queried during the lifetime or after termination of the process.The execution time of process is reported as 0 while the process is in running state and updated to actualexecution time after the process has terminated. See --help-query-accounted-apps for more info.\n'
        '\n'
        '"accounting.buffer_size"\n'
        'The size of the circular buffer that holds list of processes that can be queried for accounting stats. This is the maximum number of processes that accounting information will be stored for before information about oldest processes will get overwritten by information about new processes.\n'
        '\n'
        'Section about driver_model properties\n'
        'On Windows, the TCC, WDDM and MCDM driver models are supported. The driver model can be changed with the (-dm) or (-fdm) flags. The TCC and MCDM driver models are optimized for compute applications. I.E. kernel launch times will be quicker. The WDDM driver model is designed for graphics applications and is not recommended for compute applications. Linux does not support multiple driver models, and will always have the value of "N/A". Only for selected products. Please see feature matrix in NVML documentation.\n'
        '\n'
        '"driver_model.current"\n'
        'The driver model currently in use. Always "N/A" on Linux.\n'
        '\n'
        '"driver_model.pending"\n'
        'The driver model that will be used on the next reboot. Always "N/A" on Linux.\n'
        '\n'
        '"vbios_version"\n'
        'The BIOS of the GPU board.\n'
        '\n'
        'Section about inforom properties\n'
        "Version numbers for each object in the GPU board's inforom storage. The inforom is a small, persistent store of configuration and state data for the GPU. All inforom version fields are numerical. It can be useful to know these version numbers because some GPU features are only available with inforoms of a certain version or higher.\n"
        '\n'
        '"inforom.img" or "inforom.image"\n'
        'Global version of the infoROM image. Image version just like VBIOS version uniquely describes the exact version of the infoROM flashed on the board in contrast to infoROM object version which is only an indicator of supported features.\n'
        '\n'
        '"inforom.oem"\n'
        'Version for the OEM configuration data.\n'
        '\n'
        '"inforom.ecc"\n'
        'Version for the ECC recording data.\n'
        '\n'
        '"inforom.pwr" or "inforom.power"\n'
        'Version for the power management data.\n'
        '\n'
        '"inforom.checksum_validation"\n'
        'Inforom Checksum Validation information.\n'
        '\n'
        '"gpu_recovery_action"\n'
        "GPU recovery action information. Reports the GPU Recovery action recommended to recover from a bad state. 'N/A' indicates that the field is not supported on the current device or device configuration. An error message indicates that retrieving the field failed.\n"
        '\n'
        'Section about gom properties\n'
        'GOM allows to reduce power usage and optimize GPU throughput by disabling GPU features. Each GOM is designed to meet specific user needs.\n'
        'In "All On" mode everything is enabled and running at full speed.\n'
        'The "Compute" mode is designed for running only compute tasks. Graphics operations are not allowed.\n'
        'The "Low Double Precision" mode is designed for running graphics applications that don\'t require high bandwidth double precision.\n'
        'GOM can be changed with the (--gom) flag.\n'
        '\n'
        '"gom.current" or "gpu_operation_mode.current"\n'
        'The GOM currently in use.\n'
        '\n'
        '"gom.pending" or "gpu_operation_mode.pending"\n'
        'The GOM that will be used on the next reboot.\n'
        '\n'
        '"fan.speed"\n'
        "The fan speed value is the percent of the product's maximum noise tolerance fan speed that the device's fan is currently intended to run at. This value may exceed 100% in certain cases. Note: The reported speed is the intended fan speed. If the fan is physically blocked and unable to spin, this output will not match the actual fan speed. Many parts do not report fan speeds because they rely on cooling via fans in the surrounding enclosure.\n"
        '\n'
        '"pstate"\n'
        'The current performance state for the GPU. States range from P0 (maximum performance) to P12 (minimum performance).\n'
        '\n'
        'Section about clocks_event_reasons properties\n'
        'Retrieves information about factors that are reducing the frequency of clocks. If all event reasons are returned as "Not Active" it means that clocks are running as high as possible.\n'
        '\n'
        '"clocks_event_reasons.supported" or "clocks_throttle_reasons.supported"\n'
        'Bitmask of supported clock event reasons. See nvml.h for more details.\n'
        '\n'
        '"clocks_event_reasons.active" or "clocks_throttle_reasons.active"\n'
        'Bitmask of active clock event reasons. See nvml.h for more details.\n'
        '\n'
        '"clocks_event_reasons.gpu_idle" or "clocks_throttle_reasons.gpu_idle"\n'
        'Nothing is running on the GPU and the clocks are dropping to Idle state. This limiter may be removed in a later release.\n'
        '\n'
        '"clocks_event_reasons.applications_clocks_setting" or "clocks_throttle_reasons.applications_clocks_setting"\n'
        'GPU clocks are limited by applications clocks setting. E.g. can be changed by nvidia-smi --applications-clocks=\n'
        '\n'
        '"clocks_event_reasons.sw_power_cap" or "clocks_throttle_reasons.sw_power_cap"\n'
        'SW Power Scaling algorithm is reducing the clocks below requested clocks because the GPU is consuming too much power. E.g. SW power cap limit can be changed with nvidia-smi --power-limit=\n'
        '\n'
        '"clocks_event_reasons.hw_slowdown" or "clocks_throttle_reasons.hw_slowdown"\n'
        'HW Slowdown (reducing the core clocks by a factor of 2 or more) is engaged. This is an indicator of:\n'
        ' HW Thermal Slowdown: temperature being too high\n'
        ' HW Power Brake Slowdown: External Power Brake Assertion is triggered (e.g. by the system power supply)\n'
        ' * Power draw is too high and Fast Trigger protection is reducing the clocks\n'
        ' * May be also reported during PState or clock change\n'
        ' * This behavior may be removed in a later release\n'
        '\n'
        '"clocks_event_reasons.hw_thermal_slowdown" or "clocks_throttle_reasons.hw_thermal_slowdown"\n'
        'HW Thermal Slowdown (reducing the core clocks by a factor of 2 or more) is engaged. This is an indicator of temperature being too high\n'
        '\n'
        '"clocks_event_reasons.hw_power_brake_slowdown" or "clocks_throttle_reasons.hw_power_brake_slowdown"\n'
        'HW Power Brake Slowdown (reducing the core clocks by a factor of 2 or more) is engaged. This is an indicator of External Power Brake Assertion being triggered (e.g. by the system power supply)\n'
        '\n'
        '"clocks_event_reasons.sw_thermal_slowdown" or "clocks_throttle_reasons.sw_thermal_slowdown"\n'
        'SW Thermal capping algorithm is reducing clocks below requested clocks because GPU temperature is higher than Max Operating Temp.\n'
        '\n'
        '"clocks_event_reasons.sync_boost" or "clocks_throttle_reasons.sync_boost"\n'
        'Sync Boost This GPU has been added to a Sync boost group with nvidia-smi or DCGM in\n'
        ' * order to maximize performance per watt. All GPUs in the sync boost group\n'
        ' * will boost to the minimum possible clocks across the entire group. Look at\n'
        ' * the event reasons for other GPUs in the system to see why those GPUs are\n'
        ' * holding this one at lower clocks.\n'
        '\n'
        'Section about clocks_event_reasons_counters properties\n'
        'Retrieves counters in microseconds for events which have reduced the frequency of clocks.\n'
        '\n'
        '"clocks_event_reasons_counters.sw_power_cap"\n'
        'Amount of time SW Power Scaling algorithm has reduced the clocks below requested clocks because the GPU was consuming too much power.\n'
        '\n'
        '"clocks_event_reasons_counters.sync_boost"\n'
        'Amount of time the clock frequency of this GPU was reduced to match the minimum possible clock across the sync boost group.\n'
        '\n'
        '"clocks_event_reasons_counters.sw_thermal_slowdown"\n'
        'Amount of time SW Thermal capping algorithm has reduced clocks below requested clocks because GPU temperature was higher than Max Operating Temp.\n'
        '\n'
        '"clocks_event_reasons_counters.hw_thermal_slowdown"\n'
        'Amount of time HW Thermal Slowdown was engaged, reducing the core clocks by a factor of 2 or more, due to temperature being too high.\n'
        '\n'
        '"clocks_event_reasons_counters.hw_power_brake_slowdown"\n'
        'Amount of time External Power Brake Assertion was triggered (e.g. by the system power supply).\n'
        '\n'
        'Section about memory properties\n'
        'On-board memory information. Reported total memory is affected by ECC state. If ECC is enabled the total available memory is decreased by several percent, due to the requisite parity bits. The driver may also reserve a small amount of memory for internal use, even without active work on the GPU.\n'
        '\n'
        '"memory.total"\n'
        'Total installed GPU memory.\n'
        '\n'
        '"memory.reserved"\n'
        'Total memory reserved by the NVIDIA driver and firmware.\n'
        '\n'
        '"memory.used"\n'
        'Total memory allocated by active contexts.\n'
        '\n'
        '"memory.free"\n'
        'Total free memory.\n'
        '\n'
        '"compute_mode"\n'
        'The compute mode flag indicates whether individual or multiple compute applications may run on the GPU.\n'
        '"0: Default" means multiple contexts are allowed per device.\n'
        '"1: Exclusive_Thread", deprecated, use Exclusive_Process instead\n'
        '"2: Prohibited" means no contexts are allowed per device (no compute apps).\n'
        '"3: Exclusive_Process" means only one context is allowed per device, usable from multiple threads at a time.\n'
        '\n'
        '"compute_cap"\n'
        'The CUDA Compute Capability, represented as Major DOT Minor.\n'
        '\n'
        'Section about utilization properties\n'
        'Utilization rates report how busy each GPU is over time, and can be used to determine how much an application is using the GPUs in the system.\n'
        'Note: On MIG-enabled GPUs, querying the utilization of encoder, decoder, jpeg, ofa, gpu, and memory is not currently supported.\n'
        '\n'
        '"utilization.gpu"\n'
        'Percent of time over the past sample period during which one or more kernels was executing on the GPU.\n'
        'The sample period may be between 1 second and 1/6 second depending on the product.\n'
        '\n'
        '"utilization.memory"\n'
        'Percent of time over the past sample period during which global (device) memory was being read or written.\n'
        'The sample period may be between 1 second and 1/6 second depending on the product.\n'
        '\n'
        '"utilization.encoder"\n'
        'Percent of time over the past sample period during which one or more kernels was executing on the Encoder Engine.\n'
        'The sample period may be between 1 second and 1/6 second depending on the product.\n'
        '\n'
        '"utilization.decoder"\n'
        'Percent of time over the past sample period during which one or more kernels was executing on the Decoder Engine.\n'
        'The sample period may be between 1 second and 1/6 second depending on the product.\n'
        '\n'
        '"utilization.jpeg"\n'
        'Percent of time over the past sample period during which one or more kernels was executing on the Jpeg Engine.\n'
        'The sample period may be between 1 second and 1/6 second depending on the product.\n'
        '\n'
        '"utilization.ofa"\n'
        'Percent of time over the past sample period during which one or more kernels was executing on the Optical Flow Accelerator Engine.\n'
        'The sample period may be between 1 second and 1/6 second depending on the product.\n'
        '\n'
        'Section about encoder.stats properties\n'
        'Encoder stats report number of encoder sessions, average FPS and average latency in us for given GPUs in the system.\n'
        '\n'
        '"encoder.stats.sessionCount"\n'
        'Number of encoder sessions running on the GPU.\n'
        '\n'
        '"encoder.stats.averageFps"\n'
        'Average FPS of all sessions running on the GPU.\n'
        '\n'
        '"encoder.stats.averageLatency"\n'
        'Average latency in microseconds of all sessions running on the GPU.\n'
        '\n'
        'Section about dramEncryption.mode properties\n'
        'A flag that indicates whether DRAM Encryption support is enabled. May be either "Enabled" or "Disabled". Changes to DRAM Encryption mode require a reboot. Requires Inforom DRAM Encryption object version 1.0 or higher.\n'
        '\n'
        '"dramEncryption.mode.current"\n'
        'The DRAM Encryption mode that the GPU is currently operating under.\n'
        '\n'
        '"dramEncryption.mode.pending"\n'
        'The DRAM Encryption mode that the GPU will operate under after the next reboot.\n'
        '\n'
        'Section about ecc.mode properties\n'
        'A flag that indicates whether ECC support is enabled. May be either "Enabled" or "Disabled". Changes to ECC mode require a reboot. Requires Inforom ECC object version 1.0 or higher.\n'
        '\n'
        '"ecc.mode.current"\n'
        'The ECC mode that the GPU is currently operating under.\n'
        '\n'
        '"ecc.mode.pending"\n'
        'The ECC mode that the GPU will operate under after the next reboot.\n'
        '\n'
        'Section about ecc.errors properties\n'
        'NVIDIA GPUs can provide error counts for various types of ECC errors. Some ECC errors are either single or double bit, where single bit errors are corrected and double bit errors are uncorrectable. Texture memory errors may be correctable via resend or uncorrectable if the resend fails. These errors are available across two timescales (volatile and aggregate). Single bit ECC errors are automatically corrected by the HW and do not result in data corruption. Double bit errors are detected but not corrected. Please see the ECC documents on the web for information on compute application behavior when double bit errors occur. Volatile error counters track the number of errors detected since the last driver load. Aggregate error counts persist indefinitely and thus act as a lifetime counter.\n'
        '\n'
        '"ecc.errors.corrected.volatile.device_memory"\n'
        'Errors detected in global device memory.\n'
        '\n'
        '"ecc.errors.corrected.volatile.dram"\n'
        'Errors detected in global device memory.\n'
        '\n'
        '"ecc.errors.corrected.volatile.register_file"\n'
        'Errors detected in register file memory.\n'
        '\n'
        '"ecc.errors.corrected.volatile.l1_cache"\n'
        'Errors detected in the L1 cache.\n'
        '\n'
        '"ecc.errors.corrected.volatile.l2_cache"\n'
        'Errors detected in the L2 cache.\n'
        '\n'
        '"ecc.errors.corrected.volatile.texture_memory"\n'
        'Parity errors detected in texture memory.\n'
        '\n'
        '"ecc.errors.corrected.volatile.cbu"\n'
        'Parity errors detected in CBU.\n'
        '\n'
        '"ecc.errors.corrected.volatile.sram"\n'
        'Errors detected in global SRAMs.\n'
        '\n'
        '"ecc.errors.corrected.volatile.total"\n'
        'Total errors detected across entire chip.\n'
        '\n'
        '"ecc.errors.corrected.aggregate.device_memory"\n'
        'Errors detected in global device memory.\n'
        '\n'
        '"ecc.errors.corrected.aggregate.dram"\n'
        'Errors detected in global device memory.\n'
        '\n'
        '"ecc.errors.corrected.aggregate.register_file"\n'
        'Errors detected in register file memory.\n'
        '\n'
        '"ecc.errors.corrected.aggregate.l1_cache"\n'
        'Errors detected in the L1 cache.\n'
        '\n'
        '"ecc.errors.corrected.aggregate.l2_cache"\n'
        'Errors detected in the L2 cache.\n'
        '\n'
        '"ecc.errors.corrected.aggregate.texture_memory"\n'
        'Parity errors detected in texture memory.\n'
        '\n'
        '"ecc.errors.corrected.aggregate.cbu"\n'
        'Parity errors detected in CBU.\n'
        '\n'
        '"ecc.errors.corrected.aggregate.sram"\n'
        'Errors detected in global SRAMs.\n'
        '\n'
        '"ecc.errors.corrected.aggregate.total"\n'
        'Total errors detected across entire chip.\n'
        '\n'
        '"ecc.errors.uncorrected.volatile.device_memory"\n'
        'Errors detected in global device memory.\n'
        '\n'
        '"ecc.errors.uncorrected.volatile.dram"\n'
        'Errors detected in global device memory.\n'
        '\n'
        '"ecc.errors.uncorrected.volatile.register_file"\n'
        'Errors detected in register file memory.\n'
        '\n'
        '"ecc.errors.uncorrected.volatile.l1_cache"\n'
        'Errors detected in the L1 cache.\n'
        '\n'
        '"ecc.errors.uncorrected.volatile.l2_cache"\n'
        'Errors detected in the L2 cache.\n'
        '\n'
        '"ecc.errors.uncorrected.volatile.texture_memory"\n'
        'Parity errors detected in texture memory.\n'
        '\n'
        '"ecc.errors.uncorrected.volatile.cbu"\n'
        'Parity errors detected in CBU.\n'
        '\n'
        '"ecc.errors.uncorrected.volatile.sram"\n'
        'Errors detected in global SRAMs.\n'
        '\n'
        '"ecc.errors.uncorrected.volatile.total"\n'
        'Total errors detected across entire chip.\n'
        '\n'
        '"ecc.errors.uncorrected.aggregate.device_memory"\n'
        'Errors detected in global device memory.\n'
        '\n'
        '"ecc.errors.uncorrected.aggregate.dram"\n'
        'Errors detected in global device memory.\n'
        '\n'
        '"ecc.errors.uncorrected.aggregate.register_file"\n'
        'Errors detected in register file memory.\n'
        '\n'
        '"ecc.errors.uncorrected.aggregate.l1_cache"\n'
        'Errors detected in the L1 cache.\n'
        '\n'
        '"ecc.errors.uncorrected.aggregate.l2_cache"\n'
        'Errors detected in the L2 cache.\n'
        '\n'
        '"ecc.errors.uncorrected.aggregate.texture_memory"\n'
        'Parity errors detected in texture memory.\n'
        '\n'
        '"ecc.errors.uncorrected.aggregate.cbu"\n'
        'Parity errors detected in CBU.\n'
        '\n'
        '"ecc.errors.uncorrected.aggregate.sram"\n'
        'Errors detected in global SRAMs.\n'
        '\n'
        '"ecc.errors.uncorrected.aggregate.total"\n'
        'Total errors detected across entire chip.\n'
        '\n'
        '"ecc.errors.uncorrected.volatile.sram.parity"\n'
        'Unique volatile parity errors detected in SRAM\n'
        '\n'
        '"ecc.errors.uncorrected.volatile.sram.secded"\n'
        'Unique volatile SEC-DED errors detected in SRAM\n'
        '\n'
        '"ecc.errors.uncorrected.aggregate.sram.parity"\n'
        'Unique aggregate parity errors detected in SRAM\n'
        '\n'
        '"ecc.errors.uncorrected.aggregate.sram.secded"\n'
        'Unique aggregate SEC-DED errors detected in SRAM\n'
        '\n'
        '"ecc.errors.uncorrected.aggregate.sram.thresholdExceeded"\n'
        'Unique aggregate error threshold exceeded flag in SRAM\n'
        '\n'
        '"ecc.errors.uncorrected.aggregate.sram.l2"\n'
        'Unique aggregate errors detected in L2 cache\n'
        '\n'
        '"ecc.errors.uncorrected.aggregate.sram.sm"\n'
        'Unique aggregate errors detected in SM\n'
        '\n'
        '"ecc.errors.uncorrected.aggregate.sram.mcu"\n'
        'Unique aggregate errors detected in microcontrollers\n'
        '\n'
        '"ecc.errors.uncorrected.aggregate.sram.pcie"\n'
        'Aggregate errors detected in PCIe\n'
        '\n'
        '"ecc.errors.uncorrected.aggregate.sram.other"\n'
        'Unique aggregate SRAM errors detected not in L2 cache, SM, microcontrollers and PCIe\n'
        '\n'
        'Section about retired_pages properties\n'
        'NVIDIA GPUs can retire pages of GPU device memory when they become unreliable. This can happen when multiple single bit ECC errors occur for the same page, or on a double bit ECC error. When a page is retired, the NVIDIA driver will hide it such that no driver, or application memory allocations can access it.\n'
        '\n'
        '"retired_pages.single_bit_ecc.count" or "retired_pages.sbe"\n'
        'The number of GPU device memory pages that have been retired due to multiple single bit ECC errors.\n'
        '\n'
        '"retired_pages.double_bit.count" or "retired_pages.dbe"\n'
        'The number of GPU device memory pages that have been retired due to a double bit ECC error.\n'
        '\n'
        '"retired_pages.pending"\n'
        'Checks if any GPU device memory pages are pending retirement on the next reboot. Pages that are pending retirement can still be allocated, and may cause further reliability issues.\n'
        '\n'
        'Section about remapped_rows properties\n'
        'NVIDIA GPUs can remap bank rows of GPU device memory when they become unreliable. This can happen when multiple single bit ECC errors occur for the same row, or on a double bit ECC error. When a pending row remapping happens, GPU reset is required to complete row remapping.\n'
        '\n'
        '"remapped_rows.correctable" or "remapped_rows.sbe"\n'
        'The number of rows that have been remapped due to multiple single bit ECC errors.\n'
        '\n'
        '"remapped_rows.uncorrectable" or "remapped_rows.dbe"\n'
        'The number of rows that have been remapped due to a double bit ECC error.\n'
        '\n'
        '"remapped_rows.pending"\n'
        'Checks if any row remapping are pending on the next reboot.\n'
        '\n'
        '"remapped_rows.failure"\n'
        'Checks if any row remapping failure happens in the GPU lifespan.\n'
        '\n'
        'Section about remapped_rows.histogram properties\n'
        'The histogram of bank remap availability.\n'
        '\n'
        '"remapped_rows.histogram.max"\n'
        'The number of banks with full remap availability.\n'
        '\n'
        '"remapped_rows.histogram.high"\n'
        'The number of banks with high remap availability.\n'
        '\n'
        '"remapped_rows.histogram.partial"\n'
        'The number of banks with partial remap availability.\n'
        '\n'
        '"remapped_rows.histogram.low"\n'
        'The number of banks with low remap availability.\n'
        '\n'
        '"remapped_rows.histogram.none"\n'
        'The number of banks without remap availability.\n'
        '\n'
        '"temperature.gpu"\n'
        ' Core GPU temperature. in degrees C.\n'
        '\n'
        '"temperature.gpu.tlimit"\n'
        ' GPU T.Limit temperature. in degrees C.\n'
        '\n'
        '"temperature.memory"\n'
        ' HBM memory temperature. in degrees C.\n'
        '\n'
        '"power.management"\n'
        'A flag that indicates whether power management is enabled. Either "Supported" or "[Not Supported]". Requires Inforom PWR object version 3.0 or higher or Kepler device.\n'
        '\n'
        '"power.draw"\n'
        'The last measured power draw for the entire board, in watts. On Ampere or newer devices, returns average power draw over 1 sec. On older devices, returns instantaneous power draw. Only available if power management is supported. This reading is accurate to within +/- 5 watts.\n'
        '\n'
        '"power.draw.average" or "gpu.power.draw.average"\n'
        'The last measured average power draw for the entire board, in watts. Only available if power management is supported and Ampere (except GA100) or newer devices. This reading is accurate to within +/- 5 watts.\n'
        '\n'
        '"power.draw.instant" or "gpu.power.draw.instant"\n'
        'The last measured instant power draw for the entire board, in watts. Only available if power management is supported. This reading is accurate to within +/- 5 watts.\n'
        '\n'
        '"power.limit" or "gpu.power.requested_limit"\n'
        'The software power limit in watts. Set by software like nvidia-smi. On Kepler devices Power Limit can be adjusted using [-pl | --power-limit=] switches.\n'
        '\n'
        '"enforced.power.limit" or "gpu.power.current_limit"\n'
        "The power management algorithm's power ceiling, in watts. Total board power draw is manipulated by the power management algorithm such that it stays under this value. This value is the minimum of various power limiters.\n"
        '\n'
        '"power.default_limit" or "gpu.power.default_limit"\n'
        "The default power management algorithm's power ceiling, in watts. Power Limit will be set back to Default Power Limit after driver unload.\n"
        '\n'
        '"power.min_limit" or "gpu.power.min_limit"\n'
        'The minimum value in watts that power limit can be set to.\n'
        '\n'
        '"power.max_limit" or "gpu.power.max_limit"\n'
        'The maximum value in watts that power limit can be set to.\n'
        '\n'
        '"module.power.draw.average"\n'
        'The last measured average power draw for the entire module, in watts. This reading is accurate to within +/- 5 watts.\n'
        '\n'
        '"module.power.draw.instant"\n'
        'The last measured instant power draw for the entire module, in watts. This reading is accurate to within +/- 5 watts.\n'
        '\n'
        '"module.power.limit" or "module.power.requested_limit"\n'
        'The software power limit in watts for the entire module.\n'
        '\n'
        '"module.enforced.power.limit" or "module.power.current_limit"\n'
        "The power management algorithm's power ceiling for the entire module, in watts. This value is the minimum of various power limiters.\n"
        '\n'
        '"module.power.default_limit"\n'
        "The default power management algorithm's power ceiling for the entire module, in watts. Power Limit will be set back to Default Power Limit after driver unload.\n"
        '\n'
        '"module.power.min_limit"\n'
        'The minimum value in watts that module power limit can be set to.\n'
        '\n'
        '"module.power.max_limit"\n'
        'The maximum value in watts that module power limit can be set to.\n'
        '\n'
        '"power_smoothing.delayed_power_smoothing_supported"\n'
        'Indicates whether delayed power smoothing is supported (Yes/No).\n'
        '\n'
        '"power_smoothing.primary_power_floor"\n'
        'Current primary Power floor value in watts for power smoothing.\n'
        '\n'
        '"power_smoothing.secondary_power_floor"\n'
        'Current secondary Power floor value in watts for power smoothing.\n'
        '\n'
        '"power_smoothing.min_primary_floor_activation_offset"\n'
        'Minimum primary floor activation offset value in watts for power smoothing.\n'
        '\n'
        '"power_smoothing.min_primary_floor_activation_point"\n'
        'Minimum primary floor activation point value in watts for power smoothing.\n'
        '\n'
        '"power_smoothing.window_multiplier"\n'
        'The window multiplier value in ms for power smoothing.\n'
        '\n'
        '"power_smoothing.curr_profile.secondary_power_floor"\n'
        'Current profile secondary power floor value in watts.\n'
        '\n'
        '"power_smoothing.curr_profile.primary_floor_act_window_multiplier"\n'
        'Current profile primary floor activation window multiplier value.\n'
        '\n'
        '"power_smoothing.curr_profile.primary_floor_tar_window_multiplier"\n'
        'Current profile primary floor target window multiplier value.\n'
        '\n'
        '"power_smoothing.curr_profile.primary_floor_act_offset"\n'
        'Current profile primary floor activation offset value in watts.\n'
        '\n'
        '"power_smoothing.admin_override.secondary_power_floor"\n'
        'Admin override for secondary power floor value in watts, if set.\n'
        '\n'
        '"power_smoothing.admin_override.primary_floor_act_window_multiplier"\n'
        'Admin override for primary floor activation window multiplier value, if set.\n'
        '\n'
        '"power_smoothing.admin_override.primary_floor_tar_window_multiplier"\n'
        'Admin override for primary floor target window multiplier value, if set.\n'
        '\n'
        '"power_smoothing.admin_override.primary_floor_act_offset"\n'
        'Admin override for primary floor activation offset value in watts, if set.\n'
        '\n'
        '"clocks.current.graphics" or "clocks.gr"\n'
        'Current frequency of graphics (shader) clock.\n'
        '\n'
        '"clocks.current.sm" or "clocks.sm"\n'
        'Current frequency of SM (Streaming Multiprocessor) clock.\n'
        '\n'
        '"clocks.current.memory" or "clocks.mem"\n'
        'Current frequency of memory clock.\n'
        '\n'
        '"clocks.current.video" or "clocks.video"\n'
        'Current frequency of video encoder/decoder clock.\n'
        '\n'
        'Section about clocks.applications properties\n'
        'User specified frequency at which applications will be running at. Can be changed with [-ac | --applications-clocks] switches.\n'
        '\n'
        '"clocks.applications.graphics" or "clocks.applications.gr"\n'
        'User specified frequency of graphics (shader) clock.\n'
        '\n'
        '"clocks.applications.memory" or "clocks.applications.mem"\n'
        'User specified frequency of memory clock.\n'
        '\n'
        'Section about clocks.default_applications properties\n'
        'Default frequency at which applications will be running at. Application clocks can be changed with [-ac | --applications-clocks] switches. Application clocks can be set to default using [-rac | --reset-applications-clocks] switches.\n'
        '\n'
        '"clocks.default_applications.graphics" or "clocks.default_applications.gr"\n'
        'Default frequency of applications graphics (shader) clock.\n'
        '\n'
        '"clocks.default_applications.memory" or "clocks.default_applications.mem"\n'
        'Default frequency of applications memory clock.\n'
        '\n'
        'Section about clocks.max properties\n'
        'Maximum frequency at which parts of the GPU are design to run.\n'
        '\n'
        '"clocks.max.graphics" or "clocks.max.gr"\n'
        'Maximum frequency of graphics (shader) clock.\n'
        '\n'
        '"clocks.max.sm" or "clocks.max.sm"\n'
        'Maximum frequency of SM (Streaming Multiprocessor) clock.\n'
        '\n'
        '"clocks.max.memory" or "clocks.max.mem"\n'
        'Maximum frequency of memory clock.\n'
        '\n'
        'Section about mig.mode properties\n'
        'A flag that indicates whether MIG mode is enabled. May be either "Enabled" or "Disabled". Changes to MIG mode require a GPU reset.\n'
        '\n'
        '"mig.mode.current"\n'
        'The MIG mode that the GPU is currently operating under.\n'
        '\n'
        '"mig.mode.pending"\n'
        'The MIG mode that the GPU will operate under after reset.\n'
        '\n'
        'Section about gsp.mode properties\n'
        'A flag that indicates whether GSP firmware is enabled.May be either "Enabled" or "Disabled".\n'
        '\n'
        '"gsp.mode.current"\n'
        'The current status of GSP firmware.\n'
        '\n'
        '"gsp.mode.default"\n'
        'The default status of GSP firmware.\n'
        '\n'
        '"c2c.mode"\n'
        'A flag the indicates whether the device is in C2C mode, if supported.May be either "Enabled" or "Disabled".\n'
        '\n'
        'Section about protected_memory properties\n'
        'On-board protected memory information.\n'
        '\n'
        '"protected_memory.total"\n'
        'Total installed GPU conf compute protected memory.\n'
        '\n'
        '"protected_memory.used"\n'
        'Total conf compute protected memory allocated by active contexts.\n'
        '\n'
        '"protected_memory.free"\n'
        'Total free conf compute protected memory.\n'
        '\n'
        '"fabric.state"\n'
        'Current state of GPU fabric registration process.\n'
        '\n'
        '"fabric.status"\n'
        'Error status, valid only if gpu fabric registration state is "completed"\n'
        '\n'
        '"fabric.cliqueId"\n'
        'ID of the fabric clique to which this GPU belongs\n'
        '\n'
        '"fabric.clusterUuid"\n'
        'Uuid of the cluster to which this GPU belongs\n'
        '\n'
        '"fabric.health.summary"\n'
        'Fabric Health summary\n'
        '\n'
        '"fabric.health.bandwidth"\n'
        'Fabric Degraded bandwidth\n'
        '\n'
        '"fabric.health.route_recovery_in_progress"\n'
        'Fabric Route Recovery\n'
        '\n'
        '"fabric.health.route_unhealthy"\n'
        'Fabric Route Unhealthy\n'
        '\n'
        '"fabric.health.access_timeout_recovery"\n'
        'Fabric Access Timeout Recovery\n'
        '\n'
        '"fabric.health.incorrect_configuration"\n'
        'Fabric Incorrect Configuration\n'
        '\n'
        '"fabric.health.partition_assigned"\n'
        'Fabric Partition Assigned\n'
        '\n'
        'Section about platform properties\n'
        'Platform Information.\n'
        '\n'
        '"platform.chassis_serial_number"\n'
        'Serial number of the chassis containing this GPU.\n'
        '\n'
        '"platform.slot_number"\n'
        'The slot number in the chassis containing this GPU (includes switches).\n'
        '\n'
        '"platform.tray_index"\n'
        'The tray index within the compute slots in the chassis containing this GPU (does not include switches).\n'
        '\n'
        '"platform.host_id"\n'
        'Index of the node within the slot containing this GPU.\n'
        '\n'
        '"platform.peer_type"\n'
        'Platform indicated NVLink-peer type (e.g. switch present or not).\n'
        '\n'
        '"platform.module_id"\n'
        'ID of this GPU within the node.\n'
        '\n'
        '"platform.gpu_fabric_guid"\n'
        'Fabric ID for this GPU.\n'
        '\n'
        '"hostname"\n'
        'Hostname associated with the GPU.\n',
    'compute-apps':
        'List of valid properties to query for the switch "--query-compute-apps":\n'
        '\n'
        'Section about Active Compute Processes properties\n'
        'List of processes having compute context on the device.\n'
        '\n'
        '"timestamp"\n'
        'The timestamp of when the query was made in format "YYYY/MM/DD HH:MM:SS.msec".\n'
        '\n'
        '"gpu_name"\n'
        'The official product name of the GPU. This is an alphanumeric string. For all products.\n'
        '\n'
        '"gpu_bus_id"\n'
        'PCI bus id as "domain:bus:device.function", in hex.\n'
        '\n'
        '"gpu_serial"\n'
        'This number matches the serial number physically printed on each board. It is a globally unique immutable alphanumeric value.\n'
        '\n'
        '"gpu_uuid"\n'
        'This value is the globally unique immutable alphanumeric identifier of the GPU. It does not correspond to any physical label on the board.\n'
        '\n'
        '"pid"\n'
        'Process ID of the compute application\n'
        '\n'
        '"process_name" or "name"\n'
        'Process Name\n'
        '\n'
        '"used_gpu_memory" or "used_memory"\n'
        'Amount memory used on the device by the context. Not available on Windows when running in WDDM mode because Windows KMD manages all the memory not NVIDIA driver.\n',
    'accounted-apps':
        'List of valid properties to query for the switch "--query-accounted-apps":\n'
        '\n'
        'Section about Accounted Graphics/Compute Processes properties\n'
        'List of accounted processes having had a graphics/compute context on the device.\n'
        '\n'
        'Format options and one or more properties to be queried need to be provided as comma separated values for this switch.\n'
        'For example:\n'
        'nvidia-smi --query-accounted-apps=gpu_name,pid,time,gpu_util,mem_util,max_memory_usage --format=csv\n'
        '\n'
        'List of properties that can be queried are:\n'
        '\n'
        '"timestamp"\n'
        'The timestamp of when the query was made in format "YYYY/MM/DD HH:MM:SS.msec".\n'
        '\n'
        '"gpu_name"\n'
        'The official product name of the GPU. This is an alphanumeric string. For all products.\n'
        '\n'
        '"gpu_bus_id"\n'
        'PCI bus id as "domain:bus:device.function", in hex.\n'
        '\n'
        '"gpu_serial"\n'
        'This number matches the serial number physically printed on each board. It is a globally unique immutable alphanumeric value.\n'
        '\n'
        '"gpu_uuid"\n'
        'This value is the globally unique immutable alphanumeric identifier of the GPU. It does not correspond to any physical label on the board.\n'
        '\n'
        '"vgpu_instance"\n'
        'vGPU instance\n'
        '\n'
        '"pid"\n'
        'Process ID of the compute application\n'
        '\n'
        '"gpu_utilization" or "gpu_util"\n'
        'GPU Utilization\n'
        '\n'
        '"mem_utilization" or "mem_util"\n'
        'Percentage of GPU memory utilized on the device by the context.\n'
        '\n'
        '"max_memory_usage"\n'
        'Maximum amount memory used on the device by the context.\n'
        '\n'
        '"time"\n'
        'Amount of time in ms during which the compute context was active.\n',
    'retired-pages':
        'List of valid properties to query for the switch "--query-retired-pages":\n'
        '\n'
        '"timestamp"\n'
        'The timestamp of when the query was made in format "YYYY/MM/DD HH:MM:SS.msec".\n'
        '\n'
        '"gpu_name"\n'
        'The official product name of the GPU. This is an alphanumeric string. For all products.\n'
        '\n'
        '"gpu_bus_id"\n'
        'PCI bus id as "domain:bus:device.function", in hex.\n'
        '\n'
        '"gpu_serial"\n'
        'This number matches the serial number physically printed on each board. It is a globally unique immutable alphanumeric value.\n'
        '\n'
        '"gpu_uuid"\n'
        'This value is the globally unique immutable alphanumeric identifier of the GPU. It does not correspond to any physical label on the board.\n'
        '\n'
        '"retired_pages.address"\n'
        'Address of a retired page. Address might be different when ECC is Enabled or Disabled.\n'
        '\n'
        '"retired_pages.timestamp"\n'
        'Timestamp at which the page was retired.\n'
        '\n'
        '"retired_pages.cause"\n'
        'Reason that describes why the page was retired. Can take one of two values: \n'
        ' - Double Bit ECC - The number of GPU device memory pages that have been retired due to a double bit ECC error.\n'
        ' - Single Bit ECC - The number of GPU device memory pages that have been retired due to multiple single bit ECC errors.\n',
    'remapped-rows':
        'List of valid properties to query for the switch "--query-remapped-rows":\n'
        '\n'
        '"timestamp"\n'
        'The timestamp of when the query was made in format "YYYY/MM/DD HH:MM:SS.msec".\n'
        '\n'
        '"gpu_name"\n'
        'The official product name of the GPU. This is an alphanumeric string. For all products.\n'
        '\n'
        '"gpu_bus_id"\n'
        'PCI bus id as "domain:bus:device.function", in hex.\n'
        '\n'
        '"gpu_serial"\n'
        'This number matches the serial number physically printed on each board. It is a globally unique immutable alphanumeric value.\n'
        '\n'
        '"gpu_uuid"\n'
        'This value is the globally unique immutable alphanumeric identifier of the GPU. It does not correspond to any physical label on the board.\n'
        '\n'
        'Section about remapped_rows properties\n'
        'NVIDIA GPUs can remap bank rows of GPU device memory when they become unreliable. This can happen when multiple single bit ECC errors occur for the same row, or on a double bit ECC error. When a pending row remapping happens, GPU reset is required to complete row remapping.\n'
        '\n'
        '"remapped_rows.correctable" or "remapped_rows.sbe"\n'
        'The number of rows that have been remapped due to multiple single bit ECC errors.\n'
        '\n'
        '"remapped_rows.uncorrectable" or "remapped_rows.dbe"\n'
        'The number of rows that have been remapped due to a double bit ECC error.\n'
        '\n'
        '"remapped_rows.pending"\n'
        'Checks if any row remapping are pending on the next reboot.\n'
        '\n'
        '"remapped_rows.failure"\n'
        'Checks if any row remapping failure happens in the GPU lifespan.\n'
        '\n'
        'Section about remapped_rows.histogram properties\n'
        'The histogram of bank remap availability.\n'
        '\n'
        '"remapped_rows.histogram.max"\n'
        'The number of banks with full remap availability.\n'
        '\n'
        '"remapped_rows.histogram.high"\n'
        'The number of banks with high remap availability.\n'
        '\n'
        '"remapped_rows.histogram.partial"\n'
        'The number of banks with partial remap availability.\n'
        '\n'
        '"remapped_rows.histogram.low"\n'
        'The number of banks with low remap availability.\n'
        '\n'
        '"remapped_rows.histogram.none"\n'
        'The number of banks without remap availability.\n'
        '\n',
    'supported-clocks':
        'List of valid properties to query for the switch "--query-supported-clocks":\n'
        '\n'
        'Section about Supported Clocks properties\n'
        'List of possible memory and graphics clocks combinations that the GPU can operate on (not taking into account HW brake reduced clocks). These are the only clock combinations that can be passed to --applications-clocks flag.\n'
        '\n'
        '"timestamp"\n'
        'The timestamp of when the query was made in format "YYYY/MM/DD HH:MM:SS.msec".\n'
        '\n'
        '"gpu_name"\n'
        'The official product name of the GPU. This is an alphanumeric string. For all products.\n'
        '\n'
        '"gpu_bus_id"\n'
        'PCI bus id as "domain:bus:device.function", in hex.\n'
        '\n'
        '"gpu_serial"\n'
        'This number matches the serial number physically printed on each board. It is a globally unique immutable alphanumeric value.\n'
        '\n'
        '"gpu_uuid"\n'
        'This value is the globally unique immutable alphanumeric identifier of the GPU. It does not correspond to any physical label on the board.\n'
        '\n'
        '"memory" or "mem"\n'
        'Memory Clock\n'
        '\n'
        '"graphics" or "gr"\n'
        'Graphics Clock\n',
}
