"""What a tool says its version is, against what dpkg says it is.

_version_text's own docstring says the banners are "generated so it always
matches dpkg". That is the right design, and it held for curl, wget, bash,
python3, dpkg, systemd, openssl, nginx, tar, gzip, sed, grep, coreutils
and ssh. Two commands escaped it, in different ways.

**dmidecode** printed a literal `# dmidecode 3.4` while `dpkg -l` calls the
package 3.6-2 -- the binary and the package database disagreeing about
which dmidecode this is, and 3.4 without a date is a *2009* release. The
banner is taken from the package now, so it moves when that does.

**mawk** truncated the part that would have matched. dpkg's
`1.3.4.20250131-1` is mawk's "1.3.4 20250131": the last dotted component is
the release date, printed space-separated. The code did

    return "mawk %s\\n" % upstream("mawk").rsplit(".", 1)[0]

which throws the date away, so the one banner generated by the function
that promises to match dpkg was the one that did not. It also printed a
single line where mawk prints ten.

Two more spellings of the same question were silent: `mawk --version`
(the binary /usr/bin/awk is a symlink to, so `diff <(awk --version)
<(mawk --version)` is empty on the guest) and `awk -W version`, mawk's own
spelling, which the option loop consumed as "skip the next word".

Everything here was measured on the guest, banner text byte for byte.

Usage:  python3 verbannertest.py
"""

import re
import sys

import fakeshell

CHECKS, FAILS = [], []


def check(name, got, want, note=""):
    ok = got == want
    CHECKS.append(ok)
    if not ok:
        FAILS.append("FAIL %s\n  got  %r\n  want %r%s"
                     % (name, got, want, "\n  -- " + note if note else ""))


def shell():
    fs = fakeshell.VFS()
    return fakeshell.Shell(vfs=fs, peer="198.51.100.15", peer_port=40444)


sh = shell()


def r(cmd):
    try:
        return sh.run(cmd).rstrip("\n")
    except Exception as exc:                                   # noqa: BLE001
        return "<raised %s: %s>" % (type(exc).__name__, exc)


def pkg_version(pkg):
    """dpkg's version for a package, epoch stripped, or ""."""
    for line in r("dpkg -l %s 2>/dev/null" % pkg).splitlines():
        f = line.split()
        if len(f) > 2 and f[0] == "ii":
            return re.sub(r"^\d+:", "", f[2])
    return ""


def upstream(pkg):
    """The upstream part of a package version."""
    return pkg_version(pkg).split("-")[0].split("+")[0]


def line0(text):
    parts = text.splitlines()
    return parts[0] if parts else ""


# ------------------------------------ the banner and the package agree
CASES = (
    ("curl --version", "curl", lambda t: line0(t).split()[1]),
    ("wget --version", "wget", lambda t: line0(t).split()[2]),
    ("bash --version", "bash", lambda t: line0(t).split()[3].split("(")[0]),
    ("python3 --version", "python3", lambda t: line0(t).split()[1]),
    ("openssl version", "openssl", lambda t: line0(t).split()[1]),
    ("nginx -v", "nginx", lambda t: line0(t).rsplit("/", 1)[-1]),
    ("tar --version", "tar", lambda t: line0(t).split()[3]),
    ("gzip --version", "gzip", lambda t: line0(t).split()[1]),
    ("sed --version", "sed", lambda t: line0(t).split()[3]),
    ("grep --version", "grep", lambda t: line0(t).split()[3]),
    ("ls --version", "coreutils", lambda t: line0(t).split()[3]),
)
for cmd, pkg, extract in CASES:
    out = r(cmd + " 2>&1")
    try:
        said = extract(out)
    except (IndexError, ValueError):
        said = "<unparsable: %r>" % out[:40]
    want = upstream(pkg)
    check("%s matches dpkg's %s" % (cmd.split()[0], pkg), said, want,
          "the banner is generated from the package version, so these "
          "cannot differ")

# --------------------------------------------------- dmidecode's banner
dmi = line0(r("dmidecode 2>&1"))
check("dmidecode's banner names a version",
      dmi.startswith("# dmidecode "), True, "got %r" % dmi)
check("...and it is the packaged one",
      dmi.replace("# dmidecode ", ""), upstream("dmidecode"),
      "it was the literal 3.4 against a package calling itself 3.6-2, and "
      "a 3.4 without a date is a 2009 release")

# ------------------------------------------------------- mawk's banner
awkv = r("awk --version 2>&1")
check("awk's banner carries the release date",
      line0(awkv), "mawk %s %s" % tuple(upstream("mawk").rsplit(".", 1)),
      "dpkg's 1.3.4.20250131 is mawk's '1.3.4 20250131'; rsplit threw the "
      "date away")
check("...and the whole banner, not one line",
      len(awkv.splitlines()), 10,
      "mawk prints ten lines; we printed one")
for want in ("Copyright 2008-2024,2025, Thomas E. Dickey",
             "Copyright 1991-1996,2014, Michael D. Brennan",
             "random-funcs:       srandom/random",
             "regex-funcs:        internal",
             "compiled limits:",
             "sprintf buffer      8192",
             "maximum-integer     9223372036854775808"):
    check("awk banner has %r" % want[:34], want in awkv.splitlines(), True)

# --------------------------- and every spelling of it says the same thing
check("mawk --version equals awk --version",
      r("mawk --version 2>&1"), awkv,
      "/usr/bin/awk is a symlink to /usr/bin/mawk, so the two names print "
      "the same banner; this one was silent")
check("awk -W version equals awk --version",
      r("awk -W version 2>&1"), awkv,
      "mawk's own spelling; the option loop ate it as 'skip the next word'")
check("-W version exits 0", r("awk -W version >/dev/null 2>&1; echo $?"), "0")

# --------------------------------------------- and awk still runs programs
check("awk still runs a program",
      r("echo a b c | awk '{print $2}'"), "b",
      "the -W shortcut must not shadow real invocations")
check("...including with -W posix",
      r("echo a b c | awk -W posix '{print $3}'"), "c")
check("...and -v assignment still works",
      r("awk -v n=7 'BEGIN{print n+1}'"), "8")

for f in FAILS:
    print(" ", f)
print("   verbanner: %d checks, %d differ" % (len(CHECKS), len(FAILS)))
sys.exit(1 if FAILS else 0)
